// @ts-check
import { readFileSync } from 'node:fs';
import { unified } from '@astrojs/markdown-remark';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

/**
 * Read the configuration generated by Ductus. If the files are missing (e.g.
 * right after copying the template), the site stays operational with fallbacks.
 */
function readJson(relativePath, fallback) {
  try {
    return JSON.parse(readFileSync(new URL(relativePath, import.meta.url), 'utf8'));
  } catch {
    return fallback;
  }
}

const site = readJson('./ductus.site.json', { title: 'Documentation' });
const sidebar = readJson('./ductus.sidebar.json', []);

// UI language of the shell (sidebar group label): German only for a German
// app locale (ductus.site.json), English for everything else.
const isGermanLocale = String(site.locale ?? '').toLowerCase().startsWith('de');

/**
 * Remark plugin: ```mermaid code blocks (flowchart, journey, …) become
 * `<pre class="mermaid">` with the diagram source as text content; the client
 * script (see the head option below) renders SVG from it.
 *
 * Deliberately NO raw html node: the MDX compiler discards raw html nodes,
 * and the Ductus pages are MDX. Instead, hast data
 * (hName/hProperties/hChildren) is set — that works in Markdown AND MDX,
 * because both pipelines use mdast-util-to-hast. The text content is
 * HTML-escaped automatically along the way.
 */
function remarkMermaid() {
  /** @param {{ children?: Array<{ type: string, lang?: string | null, value?: string, children?: unknown[] }> }} node */
  const walk = (node) => {
    if (!Array.isArray(node.children)) return;
    for (let i = 0; i < node.children.length; i += 1) {
      const child = node.children[i];
      if (child.type === 'code' && child.lang === 'mermaid') {
        node.children[i] = /** @type {typeof child} */ (
          /** @type {unknown} */ ({
            type: 'mermaidDiagram',
            data: {
              hName: 'pre',
              hProperties: { className: ['mermaid'] },
              hChildren: [{ type: 'text', value: child.value ?? '' }],
            },
          })
        );
      } else {
        walk(child);
      }
    }
  };
  return walk;
}

/**
 * Client-side rendering of the Mermaid diagrams (same CDN source as
 * .ductus/graph.html). Without a network connection the import fails and the
 * code block remains as a readable fallback. Theme-aware: Starlight sets
 * data-theme ('dark'/'light') on <html>; on change, the diagram is re-rendered
 * from the preserved source text.
 */
const mermaidClientScript = `
import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';

const diagrams = Array.from(document.querySelectorAll('pre.mermaid'));

// Preserve the source text: mermaid.run() replaces the content with SVG.
for (const el of diagrams) {
  el.dataset.mermaidSource = el.textContent || '';
}

const pickTheme = () =>
  document.documentElement.dataset.theme === 'dark' ? 'dark' : 'default';

async function renderAll() {
  for (const el of diagrams) {
    el.removeAttribute('data-processed');
    el.textContent = el.dataset.mermaidSource || '';
  }
  mermaid.initialize({ startOnLoad: false, theme: pickTheme() });
  // suppressErrors: one faulty diagram does not block the others.
  await mermaid.run({ nodes: diagrams, suppressErrors: true });
}

if (diagrams.length > 0) {
  // Register the observer BEFORE the first render so that a render error
  // does not prevent reacting to theme changes.
  new MutationObserver(() => {
    renderAll();
  }).observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
  await renderAll();
}
`;

export default defineConfig({
  // Astro ≥ 6.4 renders Markdown/MDX via markdown.processor; the previously
  // common markdown.remarkPlugins is deprecated. Starlight passes the processor
  // through to MDX content as well (extendMarkdownConfig of the MDX integration).
  markdown: {
    processor: unified({ remarkPlugins: [remarkMermaid] }),
  },
  integrations: [
    starlight({
      title: site.title ?? 'Documentation',
      head: [
        {
          tag: 'script',
          attrs: { type: 'module' },
          content: mermaidClientScript,
        },
      ],
      sidebar: [
        {
          label: isGermanLocale ? 'Anleitungen' : 'Guides',
          items: sidebar,
        },
      ],
    }),
  ],
});
