// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';

/**
 * Journey template of the website mode: pure Astro without Starlight.
 *
 * Reads the data generated by Ductus (ductus.data.json in the site root). If
 * the file is missing or not valid JSON (e.g. right after copying the
 * template), the site stays operational with an empty fallback — like the
 * Starlight template. The data is embedded via Vite `define` as the constant
 * __DUCTUS_DATA__ (here import.meta.url is not yet bundled; in src/ the
 * relative file access would be unreliable at build time); src/lib/data.ts
 * normalizes it.
 */
function readJson(relativePath, fallback) {
  try {
    return JSON.parse(readFileSync(new URL(relativePath, import.meta.url), 'utf8'));
  } catch {
    return fallback;
  }
}

const ductusData = readJson('./ductus.data.json', null);

export default defineConfig({
  vite: {
    define: {
      __DUCTUS_DATA__: JSON.stringify(ductusData),
    },
  },
});
